name: Deploy to dev
on:
  push:
    branches: [dev]
jobs:
  deployment:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - env:
          NAME: ${{ vars.NAME  }}
        run: echo $NAME